# Generated by Django 5.1.7 on 2025-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_profile_twitter_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_handle',
            new_name='facebook_username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_handle',
            new_name='twitter_username',
        ),
    ]
